name:                aoc
version:             0.1.0.0
github:              "dustin/day1"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/day1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - vector
    - edit-distance
    - text
    - attoparsec
    - time
    - parallel
    - transformers
    - extra
    - array
    - JuicyPixels

executables:
  aoc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    - containers

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    - array
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-golden

benchmarks:
  aoc-bench:
    dependencies:
    - aoc
    - criterion
    - deepseq
    ghc-options:
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: bench.hs
    source-dirs: test/bench
